on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

name: 'Slack Notification'
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notify
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_CHANNEL: C0361U8AR6V
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://cdn.vox-cdn.com/thumbor/I0Kl_Nf0ZMKi1VueToDYS6tSlHw=/0x94:1494x1090/1820x1213/filters:focal(0x94:1494x1090):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/45686844/big_bird_half.0.0.jpg
        SLACK_USERNAME: Slack Notification
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
